### ISSUE TITLE
key = "true" outputs as key = 1

### ISSUE THREAD

**Issue by evansj** [terraform-providers/terraform-provider-null#32] opened 2019-06-06 13:52 UTC
### Terraform Version

0.11.14

### Affected Resource(s)

- null_data_source

### Terraform Configuration Files

```hcl
provider "null" {
  version = "~> 2.1"
}

data "null_data_source" "asg_tags" {
  count  = "${length(keys(local.tags))}"

  inputs = {
    key                 = "${element(keys(local.tags), count.index)}"
    value               = "${element(values(local.tags), count.index)}"
    propagate_at_launch = "true"
  }
}
# also tried:
# propagate_at_launch = true (no quotes)
#
# inputs = "${map("key", "${element(keys(local.tags), count.index)}",
#             "value", "${element(values(local.tags), count.index)}",
#             "propagate_at_launch", "true")}"

locals {
  tags = {
    A = "aaaa"
    B = "bbbb"
  }

  asg_tags = ["${concat(list(
    map("key", "Name",
        "value", "ECS node",
        "propagate_at_launch", "true")),
    data.null_data_source.asg_tags.*.outputs)}"]
}

output "asg_tags" {
  value = "${local.asg_tags}"
}
```

### Debug Output

https://gist.github.com/evansj/cae39bc7fa0fa69bd64a4eb36e0db5ce

### Expected Behavior

```
Outputs:

asg_tags = [
    {
        key = Name,
        propagate_at_launch = true,
        value = ECS node
    },
    {
        key = A,
        propagate_at_launch = true,
        value = aaaa
    },
    {
        key = B,
        propagate_at_launch = true,
        value = bbbb
    }
```

### Actual Behavior

```
Outputs:

asg_tags = [
    {
        key = Name,
        propagate_at_launch = true,
        value = ECS node
    },
    {
        key = A,
        propagate_at_launch = 1,
        value = aaaa
    },
    {
        key = B,
        propagate_at_launch = 1,
        value = bbbb
    }
```

### Steps to Reproduce

1. Copy the above sample code into a .tf file
2. `terraform init`
3. `terraform apply`

### References

- possibly https://github.com/hashicorp/terraform/issues/10826

**Comment by apparentlymart** [comment] 2019-06-07 00:10
Hi @evansj! Sorry for this strange behavior.

I think this hase the same root cause as hashicorp/terraform#13512, which has been fixed in the Terraform Core v0.12.0 release.

We cannot backport the fix to Terraform v0.11 because it depends on the new configuration language runtime we integrated in Terraform v0.12.0. All of the workarounds I can think of depend on new Terraform v0.12.0 features, so sadly I don't think there is a way to fix this while remaining on Terraform v0.11.14.

If you were to use v0.12.0 then this `null_data_source` approach would no longer be necessary anyway, since the conversion from a map to a list of objects could be done using the new `for` expression syntax:

```hcl
output "asg_tags" {
  value = [for t in local.tags : {
    key   = t.key
    value = t.value

    propagate_at_launch = true
  }]
}
```

Since this is already fixed in v0.12.0 and there's no feasible path to backport it to Terraform v0.11.0 or any way for the `null` provider to work around this itself, I'm going to close this out. I'm sorry I don't have a workaround to suggest for your current Terraform version.

**Closed by apparentlymart** 2019-06-07 00:10 UTC
